CREATE TABLE IF NOT EXISTS `bid` (
  `id` smallint(4) unsigned NOT NULL AUTO_INCREMENT,

  `nom_dig` varchar(50) COLLATE utf8_general_ci NOT NULL,
  `i_m_a_p_1` tinyint(2) unsigned NOT NULL,
  `i_m_a_p_2` tinyint(2) unsigned NOT NULL,
  `i_m_a_p_3` tinyint(2) unsigned NOT NULL,
  `i_m_a_p_4` tinyint(2) unsigned NOT NULL,
  `i_m_a_p_5` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_1` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_2` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_3` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_4` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_5` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_6` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_7` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_8` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_9` text,
  `i_m_b_p_10` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_11_a` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_11_b` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_12_a` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_12_b` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_13_a` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_13_b` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_14` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_15` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_16` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_17` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_18` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_19` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_20` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_21` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_22` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_23` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_24` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_25` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_26` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_27` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_28` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_29` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_30` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_31` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_32` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_33` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_34` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_35` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_36` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_37` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_38` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_39` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_40` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_41` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_42` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_43` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_44` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_45` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_46` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_47` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_48` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_49` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_50` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_51` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_52` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_53` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_54` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_55` tinyint(2) unsigned NOT NULL,
  `i_m_b_p_56_1` text,
  `i_m_b_p_56_2` text,
  `i_m_b_p_56_3` text,
  `i_m_b_p_57_1` text,
  `i_m_b_p_57_2` text,
  `i_m_b_p_57_3` text,
  `i_m_c_p_1` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_2` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_3` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_4` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_5` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_6` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_7` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_8` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_9` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_10` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_11` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_12` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_13` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_14` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_15` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_16` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_17` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_18` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_19` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_20` tinyint(2) unsigned NOT NULL,
  `i_m_c_p_21` tinyint(2) unsigned NOT NULL,
  `i_m_d_p_1` tinyint(2) unsigned NOT NULL,
  `i_m_d_p_2` tinyint(2) unsigned NOT NULL,
  `i_m_d_p_3` tinyint(2) unsigned NOT NULL,
  `i_m_d_p_1_1` tinyint(2) unsigned NOT NULL,
  `i_m_d_p_1_2` tinyint(2) unsigned NOT NULL,
  `i_m_d_p_1_3` tinyint(2) unsigned NOT NULL,
  `i_m_d_p_1_4` tinyint(2) unsigned NOT NULL,
  `i_m_d_p_1_5` tinyint(2) unsigned NOT NULL,
  `i_m_d_p_2_1` tinyint(2) unsigned NOT NULL,
  `i_m_d_p_2_2` tinyint(2) unsigned NOT NULL,
  `i_m_d_p_2_3` tinyint(2) unsigned NOT NULL,
  `i_m_d_p_2_4` tinyint(2) unsigned NOT NULL,
  `i_m_d_p_2_5` tinyint(2) unsigned NOT NULL,
  `i_m_d_p_3_1` tinyint(2) unsigned NOT NULL,
  `i_m_d_p_3_2` tinyint(2) unsigned NOT NULL,
  `i_m_d_p_3_3` tinyint(2) unsigned NOT NULL,
  `i_m_d_p_3_4` tinyint(2) unsigned NOT NULL,
  `i_m_d_p_3_5` tinyint(2) unsigned NOT NULL,
  
  `creado_el` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci AUTO_INCREMENT=1;