CREATE TABLE IF NOT EXISTS `bid2` (
  `id` smallint(4) unsigned NOT NULL AUTO_INCREMENT,
  `idusuario` smallint(4) unsigned,
  `usuario` varchar(50) COLLATE utf8_general_ci,
  `pais` varchar(50) COLLATE utf8_general_ci,
  `i_m_a_p_1` tinyint(2) unsigned DEFAULT '0',
  `i_m_a_p_2` tinyint(2) unsigned DEFAULT '0',
  `i_m_a_p_3` tinyint(2) unsigned DEFAULT '0',
  `i_m_a_p_4` tinyint(2) unsigned DEFAULT '0',
  `i_m_a_p_5` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_1` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_2` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_3` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_4` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_5` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_6` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_7` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_8` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_9_a` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_9_b` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_9_c` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_10` varchar(255) COLLATE utf8_general_ci DEFAULT '',
  `i_m_b_p_11` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_12_a` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_12_b` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_13_a` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_13_b` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_14_a` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_14_b` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_14_c` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_15_a` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_15_b` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_15_c` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_16` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_17` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_18` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_19` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_20` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_21` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_22` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_23` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_24` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_25` varchar(50) COLLATE utf8_general_ci DEFAULT '',
  `i_m_b_p_26` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_27` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_28` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_29` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_30` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_31` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_32` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_33` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_34` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_35` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_36` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_37` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_38` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_39` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_40` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_41` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_42` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_43` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_44` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_45` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_46` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_47` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_48` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_49` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_50` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_51` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_52` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_53` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_54` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_55` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_56` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_57` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_58` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_59` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_60` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_61` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_62` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_63` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_64` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_65` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_66` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_67` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_68_a` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_68_b` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_69` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_70` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_71` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_72` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_73` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_74` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_75` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_76` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_77` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_78_a` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_78_b` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_78_c` tinyint(2) unsigned DEFAULT '0',
  `i_m_b_p_79_a` varchar(255) COLLATE utf8_general_ci DEFAULT '',
  `i_m_b_p_79_b` varchar(255) COLLATE utf8_general_ci DEFAULT '',
  `i_m_b_p_79_c` varchar(255) COLLATE utf8_general_ci DEFAULT '',
  `i_m_b_p_80_a` varchar(255) COLLATE utf8_general_ci DEFAULT '',
  `i_m_b_p_80_b` varchar(255) COLLATE utf8_general_ci DEFAULT '',
  `i_m_b_p_80_c` varchar(255) COLLATE utf8_general_ci DEFAULT '',
  `i_m_c_p_1` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_2` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_3` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_4` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_5` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_6` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_7` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_8` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_9` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_10` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_11` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_12` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_13` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_14` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_15` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_16` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_17` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_18` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_19` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_20` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_21` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_22` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_23` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_24` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_25` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_26` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_27` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_28` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_29` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_30` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_31` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_32` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_33` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_34` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_35` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_36` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_37` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_38` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_39` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_40` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_41` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_42` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_43` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_44` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_45` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_46` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_47` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_48` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_49` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_50` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_51` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_52` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_53` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_54` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_55` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_56` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_57` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_58` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_59` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_60` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_61` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_62` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_63` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_64` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_65` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_66` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_67` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_68` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_69` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_70` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_71` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_72` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_73` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_74` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_75` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_76` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_77` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_78` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_79` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_80` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_81` varchar(255) COLLATE utf8_general_ci DEFAULT '',
  `i_m_c_p_82` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_83` varchar(255) COLLATE utf8_general_ci DEFAULT '',
  `i_m_c_p_84` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_85` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_86` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_87` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_88` tinyint(2) unsigned DEFAULT '0',
  `i_m_c_p_89_a` varchar(255) COLLATE utf8_general_ci DEFAULT '',
  `i_m_c_p_89_b` varchar(255) COLLATE utf8_general_ci DEFAULT '',
  `i_m_c_p_89_c` varchar(255) COLLATE utf8_general_ci DEFAULT '',
  `creado_el` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci AUTO_INCREMENT=1;